// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: comment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
SELECT id, user_id, post_id, path, depth, upvotes, downvotes, body, created_at, last_modified_at FROM insert_comment(
  p_user_id := $1,
  p_post_id := $2,
  p_parent_path := $4,
  p_body := $3
)
`

type CreateCommentParams struct {
	PUserID     int64       `json:"p_user_id"`
	PPostID     int64       `json:"p_post_id"`
	PBody       string      `json:"p_body"`
	PParentPath pgtype.Text `json:"p_parent_path"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PUserID,
		arg.PPostID,
		arg.PBody,
		arg.PParentPath,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Path,
		&i.Depth,
		&i.Upvotes,
		&i.Downvotes,
		&i.Body,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, user_id, post_id, path, depth, upvotes, downvotes, body, created_at, last_modified_at FROM comments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Path,
		&i.Depth,
		&i.Upvotes,
		&i.Downvotes,
		&i.Body,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET 
  upvotes = upvotes + COALESCE($2, 0),
  downvotes = downvotes + COALESCE($3, 0),
  body = COALESCE($4, body)
WHERE id = $1
RETURNING id, user_id, post_id, path, depth, upvotes, downvotes, body, created_at, last_modified_at
`

type UpdateCommentParams struct {
	ID             int64       `json:"id"`
	DeltaUpvotes   pgtype.Int8 `json:"delta_upvotes"`
	DeltaDownvotes pgtype.Int8 `json:"delta_downvotes"`
	Body           pgtype.Text `json:"body"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment,
		arg.ID,
		arg.DeltaUpvotes,
		arg.DeltaDownvotes,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Path,
		&i.Depth,
		&i.Upvotes,
		&i.Downvotes,
		&i.Body,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}
