// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: createPost :one
INSERT INTO posts (
  user_id, 
  title,
  topics,
  body
) VALUES (
  $1, $2, $3, $4
) RETURNING id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity
`

type createPostParams struct {
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
	Topics []byte `json:"topics"`
	Body   []byte `json:"body"`
}

func (q *Queries) createPost(ctx context.Context, arg createPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.Title,
		arg.Topics,
		arg.Body,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topics,
		&i.Body,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.Popularity,
	)
	return i, err
}

const deletePost = `-- name: deletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) deletePost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostVote = `-- name: deletePostVote :exec
SELECT delete_post_vote(
  p_post_id := $1,
  p_user_id := $2
)
`

type deletePostVoteParams struct {
	PPostID int64 `json:"p_post_id"`
	PUserID int64 `json:"p_user_id"`
}

func (q *Queries) deletePostVote(ctx context.Context, arg deletePostVoteParams) error {
	_, err := q.db.Exec(ctx, deletePostVote, arg.PPostID, arg.PUserID)
	return err
}

const getNewestPosts = `-- name: getNewestPosts :many
SELECT id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity, user_display_name, user_profile_img_url FROM posts_with_author
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type getNewestPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) getNewestPosts(ctx context.Context, arg getNewestPostsParams) ([]PostsWithAuthor, error) {
	rows, err := q.db.Query(ctx, getNewestPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostsWithAuthor{}
	for rows.Next() {
		var i PostsWithAuthor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Topics,
			&i.Body,
			&i.Upvotes,
			&i.Downvotes,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.Popularity,
			&i.UserDisplayName,
			&i.UserProfileImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOldestPosts = `-- name: getOldestPosts :many
SELECT id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity, user_display_name, user_profile_img_url FROM posts_with_author
ORDER BY created_at ASC, id ASC
LIMIT $1 OFFSET $2
`

type getOldestPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) getOldestPosts(ctx context.Context, arg getOldestPostsParams) ([]PostsWithAuthor, error) {
	rows, err := q.db.Query(ctx, getOldestPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostsWithAuthor{}
	for rows.Next() {
		var i PostsWithAuthor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Topics,
			&i.Body,
			&i.Upvotes,
			&i.Downvotes,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.Popularity,
			&i.UserDisplayName,
			&i.UserProfileImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: getPost :one
SELECT id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity FROM posts
WHERE id = $1
LIMIT 1
`

func (q *Queries) getPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topics,
		&i.Body,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.Popularity,
	)
	return i, err
}

const getPostWithAuthor = `-- name: getPostWithAuthor :one
SELECT id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity, user_display_name, user_profile_img_url FROM posts_with_author
WHERE id = $1
LIMIT 1
`

func (q *Queries) getPostWithAuthor(ctx context.Context, id int64) (PostsWithAuthor, error) {
	row := q.db.QueryRow(ctx, getPostWithAuthor, id)
	var i PostsWithAuthor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topics,
		&i.Body,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.Popularity,
		&i.UserDisplayName,
		&i.UserProfileImgUrl,
	)
	return i, err
}

const getPostsByPopularity = `-- name: getPostsByPopularity :many
SELECT id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity, user_display_name, user_profile_img_url FROM posts_with_author
WHERE p.created_at >= (NOW() - $3::INTERVAL)
ORDER BY (p.upvotes - p.downvotes) DESC
LIMIT $1
OFFSET $2
`

type getPostsByPopularityParams struct {
	Limit    int32           `json:"limit"`
	Offset   int32           `json:"offset"`
	Interval pgtype.Interval `json:"interval"`
}

func (q *Queries) getPostsByPopularity(ctx context.Context, arg getPostsByPopularityParams) ([]PostsWithAuthor, error) {
	rows, err := q.db.Query(ctx, getPostsByPopularity, arg.Limit, arg.Offset, arg.Interval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostsWithAuthor{}
	for rows.Next() {
		var i PostsWithAuthor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Topics,
			&i.Body,
			&i.Upvotes,
			&i.Downvotes,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.Popularity,
			&i.UserDisplayName,
			&i.UserProfileImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: updatePost :one
UPDATE posts
SET 
  title = COALESCE($2, title),
  body = COALESCE($3, body),
  topics = COALESCE($4, topics),
  last_modified_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity
`

type updatePostParams struct {
	ID     int64       `json:"id"`
	Title  pgtype.Text `json:"title"`
	Body   []byte      `json:"body"`
	Topics []byte      `json:"topics"`
}

func (q *Queries) updatePost(ctx context.Context, arg updatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Topics,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topics,
		&i.Body,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.Popularity,
	)
	return i, err
}

const votePost = `-- name: votePost :one
SELECT id, user_id, title, topics, body, upvotes, downvotes, created_at, last_modified_at, popularity FROM vote_post(
  p_user_id := $1,
  p_post_id := $2,
  p_vote := $3   
)
`

type votePostParams struct {
	PUserID int64 `json:"p_user_id"`
	PPostID int64 `json:"p_post_id"`
	PVote   int32 `json:"p_vote"`
}

func (q *Queries) votePost(ctx context.Context, arg votePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, votePost, arg.PUserID, arg.PPostID, arg.PVote)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Topics,
		&i.Body,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.Popularity,
	)
	return i, err
}
