// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_vote.sql

package db

import (
	"context"
)

const getPostVote = `-- name: GetPostVote :one
SELECT id, user_id, post_id, vote, created_at, last_modified_at from post_votes
WHERE user_id = $1 AND post_id = $2
LIMIT 1
`

type GetPostVoteParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) GetPostVote(ctx context.Context, arg GetPostVoteParams) (PostVote, error) {
	row := q.db.QueryRow(ctx, getPostVote, arg.UserID, arg.PostID)
	var i PostVote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Vote,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}
