// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	createComment(ctx context.Context, arg createCommentParams) (Comment, error)
	createPost(ctx context.Context, arg createPostParams) (Post, error)
	createSession(ctx context.Context, arg createSessionParams) (Session, error)
	createUser(ctx context.Context, arg createUserParams) (User, error)
	createWebauthnCredentials(ctx context.Context, arg createWebauthnCredentialsParams) (WebauthnCredential, error)
	deleteCommentIfLeaf(ctx context.Context, arg deleteCommentIfLeafParams) (deleteCommentIfLeafRow, error)
	deletePost(ctx context.Context, id int64) error
	deletePostVote(ctx context.Context, arg deletePostVoteParams) error
	deleteUserCredentials(ctx context.Context, userID int64) error
	deleteUserSessions(ctx context.Context, userID int64) error
	emailExists(ctx context.Context, email string) (bool, error)
	getActiveUsers(ctx context.Context, limit int32) ([]User, error)
	getComment(ctx context.Context, id int64) (Comment, error)
	getCommentVote(ctx context.Context, arg getCommentVoteParams) (CommentVote, error)
	getCommentWithAuthor(ctx context.Context, id int64) (CommentsWithAuthor, error)
	getCommentWithLock(ctx context.Context, id int64) (Comment, error)
	getCommentsByPopularity(ctx context.Context, arg getCommentsByPopularityParams) ([]CommentsWithAuthor, error)
	getCredentialsByID(ctx context.Context, id []byte) (WebauthnCredential, error)
	getNewestComments(ctx context.Context, arg getNewestCommentsParams) ([]CommentsWithAuthor, error)
	getNewestPosts(ctx context.Context, arg getNewestPostsParams) ([]PostsWithAuthor, error)
	getOldestComments(ctx context.Context, arg getOldestCommentsParams) ([]CommentsWithAuthor, error)
	getOldestPosts(ctx context.Context, arg getOldestPostsParams) ([]PostsWithAuthor, error)
	getPost(ctx context.Context, id int64) (Post, error)
	getPostVote(ctx context.Context, arg getPostVoteParams) (PostVote, error)
	getPostWithAuthor(ctx context.Context, id int64) (PostsWithAuthor, error)
	getPostsByPopularity(ctx context.Context, arg getPostsByPopularityParams) ([]PostsWithAuthor, error)
	getSession(ctx context.Context, id uuid.UUID) (Session, error)
	getUser(ctx context.Context, id int64) (User, error)
	getUserByEmail(ctx context.Context, email string) (User, error)
	getUserByUsername(ctx context.Context, username string) (User, error)
	getUserCredentials(ctx context.Context, userID int64) ([]WebauthnCredential, error)
	listSessionsByUser(ctx context.Context, userID int64) ([]Session, error)
	listUserCredentials(ctx context.Context, userID int64) ([]WebauthnCredential, error)
	softDeleteComment(ctx context.Context, id int64) (Comment, error)
	softDeleteUser(ctx context.Context, pUserID int64) (softDeleteUserRow, error)
	updateComment(ctx context.Context, arg updateCommentParams) (updateCommentRow, error)
	updateCommentPopularity(ctx context.Context, arg updateCommentPopularityParams) (Comment, error)
	updateCredentialSignCount(ctx context.Context, arg updateCredentialSignCountParams) error
	updatePost(ctx context.Context, arg updatePostParams) (Post, error)
	updateUser(ctx context.Context, arg updateUserParams) (updateUserRow, error)
	upsertCommentVote(ctx context.Context, arg upsertCommentVoteParams) (upsertCommentVoteRow, error)
	usernameExists(ctx context.Context, username string) (bool, error)
	votePost(ctx context.Context, arg votePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
