// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email, last_modified_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
		&i.LastModifiedAt,
	)
	return i, err
}

const testUtilGetActiveUsers = `-- name: TestUtilGetActiveUsers :many
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email, last_modified_at FROM users
WHERE is_deleted = FALSE
LIMIT $1
`

func (q *Queries) TestUtilGetActiveUsers(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.Query(ctx, testUtilGetActiveUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.WebauthnUserHandle,
			&i.ProfileImgUrl,
			&i.Email,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DisplayName,
			&i.ArchivedUsername,
			&i.ArchivedEmail,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: createUser :one
INSERT INTO users (
  username, 
  display_name,
  profile_img_url,
  email,
  webauthn_user_handle
) VALUES (
  $1, $1, $2, $3, $4
) RETURNING id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email, last_modified_at
`

type createUserParams struct {
	Username           string      `json:"username"`
	ProfileImgUrl      pgtype.Text `json:"profile_img_url"`
	Email              string      `json:"email"`
	WebauthnUserHandle []byte      `json:"webauthn_user_handle"`
}

func (q *Queries) createUser(ctx context.Context, arg createUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.ProfileImgUrl,
		arg.Email,
		arg.WebauthnUserHandle,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
		&i.LastModifiedAt,
	)
	return i, err
}

const emailExists = `-- name: emailExists :one
SELECT EXISTS (SELECT 1 from users WHERE email = $1) AS email_exists
`

func (q *Queries) emailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const getUser = `-- name: getUser :one
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email, last_modified_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) getUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
		&i.LastModifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: getUserByEmail :one
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email, last_modified_at FROM users
WHERE email = $1
`

func (q *Queries) getUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
		&i.LastModifiedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: softDeleteUser :one
SELECT 
  id::BIGINT AS id,
  username::TEXT AS username,
  display_name::TEXT AS display_name,
  email::TEXT AS email,
  profile_img_url::optional_string AS profile_img_url ,
  is_deleted::BOOLEAN AS is_deleted,
  deleted_at::TIMESTAMPTZ AS deleted_at,
  last_modified_at::TIMESTAMPTZ AS last_modified_at,
  success::BOOLEAN AS success
FROM soft_delete_user(
  p_user_id := $1
)
`

type softDeleteUserRow struct {
	ID             int64       `json:"id"`
	Username       string      `json:"username"`
	DisplayName    string      `json:"display_name"`
	Email          string      `json:"email"`
	ProfileImgUrl  pgtype.Text `json:"profile_img_url"`
	IsDeleted      bool        `json:"is_deleted"`
	DeletedAt      time.Time   `json:"deleted_at"`
	LastModifiedAt time.Time   `json:"last_modified_at"`
	Success        bool        `json:"success"`
}

func (q *Queries) softDeleteUser(ctx context.Context, pUserID int64) (softDeleteUserRow, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, pUserID)
	var i softDeleteUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.ProfileImgUrl,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.LastModifiedAt,
		&i.Success,
	)
	return i, err
}

const updateUser = `-- name: updateUser :one
SELECT 
  id::BIGINT AS id,
	username::TEXT AS username,
	email::TEXT AS email,
	profile_img_url::optional_string AS profile_img_url,
	is_deleted::BOOLEAN AS is_deleted,
	last_modified_at::TIMESTAMPTZ AS last_modified_at,
	updated::BOOLEAN AS updated
FROM update_user(
  p_user_id := $1,
  p_username := $2,
  p_email := $3,
  p_profile_img_url := $4
)
`

type updateUserParams struct {
	PUserID       int64       `json:"p_user_id"`
	Username      pgtype.Text `json:"username"`
	Email         pgtype.Text `json:"email"`
	ProfileImgUrl pgtype.Text `json:"profile_img_url"`
}

type updateUserRow struct {
	ID             int64       `json:"id"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	ProfileImgUrl  pgtype.Text `json:"profile_img_url"`
	IsDeleted      bool        `json:"is_deleted"`
	LastModifiedAt time.Time   `json:"last_modified_at"`
	Updated        bool        `json:"updated"`
}

func (q *Queries) updateUser(ctx context.Context, arg updateUserParams) (updateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.PUserID,
		arg.Username,
		arg.Email,
		arg.ProfileImgUrl,
	)
	var i updateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.ProfileImgUrl,
		&i.IsDeleted,
		&i.LastModifiedAt,
		&i.Updated,
	)
	return i, err
}

const usernameExists = `-- name: usernameExists :one
SELECT EXISTS (SELECT 1 from users WHERE username = $1) AS username_exists
`

func (q *Queries) usernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var username_exists bool
	err := row.Scan(&username_exists)
	return username_exists, err
}
