// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (SELECT 1 from users WHERE email = $1) AS email_exists
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
	)
	return i, err
}

const testUtilGetActiveUsers = `-- name: TestUtilGetActiveUsers :many
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email FROM users
WHERE is_deleted = FALSE
LIMIT $1
`

func (q *Queries) TestUtilGetActiveUsers(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.Query(ctx, testUtilGetActiveUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.WebauthnUserHandle,
			&i.ProfileImgUrl,
			&i.Email,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DisplayName,
			&i.ArchivedUsername,
			&i.ArchivedEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  username = COALESCE($2, username),
  display_name = COALESCE($2, display_name),
  archived_username = COALESCE($2, archived_username),
  email = COALESCE($3, email),
  archived_email = COALESCE($3, archived_email),
  profile_img_url = COALESCE($4, profile_img_url),
  last_modified_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email
`

type UpdateUserParams struct {
	ID            int64       `json:"id"`
	Username      pgtype.Text `json:"username"`
	Email         pgtype.Text `json:"email"`
	ProfileImgUrl pgtype.Text `json:"profile_img_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.ProfileImgUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
	)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (SELECT 1 from users WHERE username = $1) AS username_exists
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var username_exists bool
	err := row.Scan(&username_exists)
	return username_exists, err
}

const createUser = `-- name: createUser :one
INSERT INTO users (
  username, 
  display_name,
  profile_img_url,
  email,
  webauthn_user_handle
) VALUES (
  $1, $1, $2, $3, $4
) RETURNING id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email
`

type createUserParams struct {
	Username           string      `json:"username"`
	ProfileImgUrl      pgtype.Text `json:"profile_img_url"`
	Email              string      `json:"email"`
	WebauthnUserHandle []byte      `json:"webauthn_user_handle"`
}

func (q *Queries) createUser(ctx context.Context, arg createUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.ProfileImgUrl,
		arg.Email,
		arg.WebauthnUserHandle,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
	)
	return i, err
}

const getUser = `-- name: getUser :one
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) getUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
	)
	return i, err
}

const getUserByEmail = `-- name: getUserByEmail :one
SELECT id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email FROM users
WHERE email = $1
`

func (q *Queries) getUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
	)
	return i, err
}

const softDeleteUser = `-- name: softDeleteUser :one
UPDATE users
SET
  is_deleted = TRUE,
  display_name = '[deleted]',
  deleted_at = NOW(),
  archived_username = username,
  archived_email    = email,
  username = CONCAT('deleted_user_', id),
  email    = CONCAT('deleted_', id, '@invalid.local'),
  profile_img_url = ''
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, username, webauthn_user_handle, profile_img_url, email, created_at, is_deleted, deleted_at, display_name, archived_username, archived_email
`

func (q *Queries) softDeleteUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WebauthnUserHandle,
		&i.ProfileImgUrl,
		&i.Email,
		&i.CreatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DisplayName,
		&i.ArchivedUsername,
		&i.ArchivedEmail,
	)
	return i, err
}
