// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Drolfothesgnir/shitposter/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination db/mock/store.go github.com/Drolfothesgnir/shitposter/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/Drolfothesgnir/shitposter/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateUserWithCredentialsTx mocks base method.
func (m *MockStore) CreateUserWithCredentialsTx(ctx context.Context, arg db.CreateUserWithCredentialsTxParams) (db.CreateUserWithCredentialsTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWithCredentialsTx", ctx, arg)
	ret0, _ := ret[0].(db.CreateUserWithCredentialsTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserWithCredentialsTx indicates an expected call of CreateUserWithCredentialsTx.
func (mr *MockStoreMockRecorder) CreateUserWithCredentialsTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWithCredentialsTx", reflect.TypeOf((*MockStore)(nil).CreateUserWithCredentialsTx), ctx, arg)
}

// DeleteCommentTx mocks base method.
func (m *MockStore) DeleteCommentTx(ctx context.Context, arg db.DeleteCommentTxParams) (db.DeleteCommentTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommentTx", ctx, arg)
	ret0, _ := ret[0].(db.DeleteCommentTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentTx indicates an expected call of DeleteCommentTx.
func (mr *MockStoreMockRecorder) DeleteCommentTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentTx", reflect.TypeOf((*MockStore)(nil).DeleteCommentTx), ctx, arg)
}

// InsertCommentTx mocks base method.
func (m *MockStore) InsertCommentTx(ctx context.Context, arg db.InsertCommentTxParams) (db.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCommentTx", ctx, arg)
	ret0, _ := ret[0].(db.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCommentTx indicates an expected call of InsertCommentTx.
func (mr *MockStoreMockRecorder) InsertCommentTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCommentTx", reflect.TypeOf((*MockStore)(nil).InsertCommentTx), ctx, arg)
}

// QueryComments mocks base method.
func (m *MockStore) QueryComments(ctx context.Context, query db.CommentQuery) ([]db.CommentsWithAuthor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryComments", ctx, query)
	ret0, _ := ret[0].([]db.CommentsWithAuthor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryComments indicates an expected call of QueryComments.
func (mr *MockStoreMockRecorder) QueryComments(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryComments", reflect.TypeOf((*MockStore)(nil).QueryComments), ctx, query)
}

// Shutdown mocks base method.
func (m *MockStore) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockStoreMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockStore)(nil).Shutdown))
}

// SoftDeleteUserTx mocks base method.
func (m *MockStore) SoftDeleteUserTx(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteUserTx", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteUserTx indicates an expected call of SoftDeleteUserTx.
func (mr *MockStoreMockRecorder) SoftDeleteUserTx(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteUserTx", reflect.TypeOf((*MockStore)(nil).SoftDeleteUserTx), ctx, userID)
}

// UpdateComment mocks base method.
func (m *MockStore) UpdateComment(ctx context.Context, arg db.UpdateCommentParams) (db.UpdateCommentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, arg)
	ret0, _ := ret[0].(db.UpdateCommentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockStoreMockRecorder) UpdateComment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockStore)(nil).UpdateComment), ctx, arg)
}

// VoteCommentTx mocks base method.
func (m *MockStore) VoteCommentTx(ctx context.Context, arg db.VoteCommentTxParams) (db.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VoteCommentTx", ctx, arg)
	ret0, _ := ret[0].(db.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VoteCommentTx indicates an expected call of VoteCommentTx.
func (mr *MockStoreMockRecorder) VoteCommentTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteCommentTx", reflect.TypeOf((*MockStore)(nil).VoteCommentTx), ctx, arg)
}
